// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThoughtInfo: typeof import('./src/components/thought-info.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VChip: typeof import('vuetify/components')['VChip']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VFileInput: typeof import('vuetify/components')['VFileInput']
    VForm: typeof import('vuetify/components')['VForm']
    VIcon: typeof import('vuetify/components')['VIcon']
    VImg: typeof import('vuetify/components')['VImg']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemSubtitle: typeof import('vuetify/components')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VolInfo: typeof import('./src/components/vol-info.vue')['default']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VRow: typeof import('vuetify/components')['VRow']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VTable: typeof import('vuetify/components')['VTable']
    VTextarea: typeof import('vuetify/components')['VTextarea']
    VTextField: typeof import('vuetify/components')['VTextField']
    VThemeProvider: typeof import('vuetify/components')['VThemeProvider']
  }
}
