// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignerList: typeof import('./src/components/signer-list.vue')['default']
    StuVolList: typeof import('./src/components/stu-vol-list.vue')['default']
    UserInfo: typeof import('./src/components/user-info.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VChip: typeof import('vuetify/components')['VChip']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VForm: typeof import('vuetify/components')['VForm']
    VIcon: typeof import('vuetify/components')['VIcon']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemContent: typeof import('vuetify/components')['VListItemContent']
    VListItemGroup: typeof import('vuetify/components')['VListItemGroup']
    VListItemSubtitle: typeof import('vuetify/components')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VolCert: typeof import('./src/components/vol-cert.vue')['default']
    VolInfo: typeof import('./src/components/vol-info.vue')['default']
    VolReward: typeof import('./src/components/vol-reward.vue')['default']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VTextField: typeof import('vuetify/components')['VTextField']
  }
}
