// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignerList: typeof import('./src/components/signer-list.vue')['default']
    StuVolList: typeof import('./src/components/stu-vol-list.vue')['default']
    UserInfo: typeof import('./src/components/user-info.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDivider: typeof import('vuetify/components')['VDivider']
    VIcon: typeof import('vuetify/components')['VIcon']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemAvatar: typeof import('vuetify/components')['VListItemAvatar']
    VListItemContent: typeof import('vuetify/components')['VListItemContent']
    VListItemIcon: typeof import('vuetify/components')['VListItemIcon']
    VListItemSubtitle: typeof import('vuetify/components')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VolCert: typeof import('./src/components/vol-cert.vue')['default']
    VolInfo: typeof import('./src/components/vol-info.vue')['default']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
  }
}
